# Generated by Django 6.0.3 on 2026-04-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=2)),
                ('dueños', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
